Repository duck-map-project/duck-map-fe, pull requests merged in 2023-06, with the labels that each got.

#40 Feat: Manageitem component 추가
  src/components/ManageItem.tsx
Labels: feature

#8 favicon 위치 변경
  src/images/favicon
  src/images/favicon/android-chrome-192x192.png
  src/images/favicon/android-chrome-512x512.png
  src/images/favicon/apple-touch-icon.png
  src/images/favicon/browserconfig.xml
  src/images/favicon/favicon-16x16.png
  src/images/favicon/favicon-32x32.png
  src/images/favicon/favicon.ico
  src/images/favicon/mstile-150x150.png
  src/images/favicon/safari-pinned-tab.svg
  src/images/favicon/site.webmanifest
Labels: feature

#46 사용자 인증 관련 기능 구현 - #43 #44 #45
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/client.ts
  src/hooks/useInput.ts
  src/pages/SignPage/Signin.tsx
Labels: feature

#51 이미지프리뷰함수 hook으로 분리
  src/hooks/usePreviewImage.ts
  src/pages/editReviewPage/EditReview.tsx
Labels: feature

#52 이미지 업로드 화면 추가 및 usePreviewImage hook 적용
  src/pages/SignPage/Signup.tsx
Labels: feature

#55 Context API로 인증관련 기능 구현
  src/App.tsx
  src/api/authApi.ts
  src/components/Dropdown.tsx
  src/components/Header.tsx
  src/contexts/AuthContext.tsx
  src/hooks/useAuth.ts
  src/pages/SignPage/Signin.tsx
  src/pages/SignPage/Signup.tsx
  src/types/auth.ts
Labels: feature

#60 비밀번호 일치 유효성 검사 기능 추가 및 적용
  src/components/AuthInput.tsx
  src/pages/SignPage/Signup.tsx
Labels: feature

#61 회원가입 페이지 모든 input 작성 여부 검사 구현
  src/components/Button.tsx
  src/pages/SignPage/Signup.tsx
Labels: feature

#64 회원가입, 로그인 페이지 텍스트 형식 유효성 검사(리펙토링 예정)
  src/components/AuthInput.tsx
  src/hooks/useInputValidation.ts
  src/pages/SignPage/Signin.tsx
  src/pages/SignPage/Signup.tsx
Labels: feature

#66 Fix: 비밀번호 정규표현식 변경
  src/hooks/useInputValidation.ts
Labels: fix

#69 Fix: 스타일드 컴포넌트 clicked 변수 에러 핸들링
  src/components/SortButton.tsx
Labels: fix

#70 회원가입, 로그인 form 유효성 검사 리펙토링
  src/api/authApi.ts
  src/components/AuthInput.tsx
  src/hooks/useForm.ts
  src/hooks/useInputValidation.ts
  src/pages/SignPage/SignStyle.tsx
  src/pages/SignPage/Signin.tsx
  src/pages/SignPage/Signup.tsx
  src/types/auth.ts
  src/utils/validates.ts
Labels: fix

#74 Feat: netilfy.toml 추가
  netlify.toml
Labels: feature

#76 Feature/404 redirect
  src/pages/NotFoundPage/NotFound.tsx
  src/pages/NotFoundPage/NotFoundStyle.ts
  src/router.tsx
Labels: feature

#78 인증 관련 로직 리펙토링
  src/App.tsx
  src/api/authApi.ts
  src/api/client.ts
  src/components/Header.tsx
  src/hooks/useAuth.ts
  src/router.tsx
Labels: fix

#82 Feat: Mypage 페이지 추가
  src/components/ManageItem.tsx
  src/pages/MyPage/MyBookmark.tsx
  src/pages/MyPage/MyEvent.tsx
  src/pages/MyPage/MyInfoEdit.tsx
  src/pages/MyPage/MyLike.tsx
  src/pages/MyPage/MyPageStyle.tsx
  src/pages/MyPage/Myreview.tsx
Labels: feature

#83 Fix: mypage 라우트 연결 및 프리티어 적용
  src/components/Dropdown.tsx
  src/components/ManageItem.tsx
  src/pages/MyPage/MyBookmark.tsx
  src/pages/MyPage/MyEvent.tsx
  src/pages/MyPage/MyInfoEdit.tsx
  src/pages/MyPage/MyLike.tsx
  src/pages/MyPage/Myreview.tsx
  src/pages/NotFoundPage/NotFound.tsx
  src/router.tsx
Labels: fix

#84 인증 관련 api 에러 처리
  src/api/authApi.ts
  src/components/Dropdown.tsx
  src/hooks/useAuth.ts
  src/hooks/useForm.ts
  src/index.tsx
  src/pages/MyPage/MyBookmark.tsx
  src/pages/NotFoundPage/NotFound.tsx
  src/pages/SignPage/SignStyle.tsx
  src/pages/SignPage/Signin.tsx
  src/pages/SignPage/Signup.tsx
  src/router.tsx
Labels: feature, fix

#86 로그인 후 유저 정보 받아오기
  src/hooks/useAuth.ts
Labels: feature

#89 비밀번호 재설정 관련 UI 작업
  src/assets/close.svg
  src/components/AuthInput.tsx
  src/components/ResetPasswordModal.tsx
  src/pages/ResetPasswordPage/ResetComplete.tsx
  src/pages/ResetPasswordPage/ResetPassword.tsx
  src/pages/SignPage/Signin.tsx
Labels: feature

#91 리프레쉬 토큰 구현
  src/api/authApi.ts
  src/hooks/useAuth.ts
  src/hooks/useLocalStarage.ts
Labels: feature

#93 Feat: Svg file update
  src/assets/icon _search.svg
  src/components/Dropdown.tsx
  src/components/EventListItem.tsx
  src/logo/logo.ai
  src/logo/logo.png
  src/logo/logoc.ai
  src/logo/logoc.png
  src/pages/MyPage/MyBookmark.tsx
  src/pages/MyPage/MyEvent.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyPageStyle.tsx
  src/pages/MyPage/feedData.json
  src/pages/eventListPage/EventList.tsx
  src/router.tsx
Labels: feature

#99 메인 페이지에 표시할 오늘 진행 중인 이벤트의 해시태그를 가져오는 API 호출
  src/api/evnet.ts
  src/components/Billboard.tsx
Labels: feature

#101 메인 페이지에 표시할 리뷰 목록을 가져오는 API 호출
  src/api/event.ts
  src/components/Billboard.tsx
  src/pages/mainPage/Main.tsx
  src/pages/mainPage/MainStyle.tsx
Labels: feature

#108 Feature/event list api
  src/api/event.ts
  src/components/EventListItem.tsx
  src/components/Tag.tsx
  src/pages/eventListPage/EventList.tsx
  src/types/eventService.ts
Labels: feature

#113 이벤트 페이지에서 EventListItem 클릭 시 EventListDetail로 변경 및 자세히 보기 클릭 시 해당 이벤트 상세 페이지로 이동
  src/components/EventListItem.tsx
  src/components/EventListItemDetail.tsx
  src/components/Tag.tsx
  src/pages/eventListPage/EventList.tsx
  src/router.tsx
Labels: feature

#116 Feat: EventListItem, EventListItemDetail 컴포넌트 스타일 변경
  src/components/EventListItem.tsx
  src/components/EventListItemDetail.tsx
Labels: fix

#117 비밀번호 재설정 구현
  src/api/authApi.ts
  src/components/ResetPasswordModal.tsx
  src/hooks/useForm.ts
  src/pages/ResetPasswordPage/ResetPassword.tsx
  src/pages/SignPage/Signin.tsx
  src/pages/SignPage/Signup.tsx
  src/utils/validates.ts
Labels: feature, fix

#120 Feat: 비밀번호 재설정 페이지 라우팅
  src/router.tsx
Labels: feature

#121 이벤트 목록 api 실제 적용
  src/api/client.ts
  src/api/event.ts
  src/pages/eventListPage/EventList.tsx
  src/types/eventService.ts
Labels: feature
