Repository duck-map-project/duck-map-fe, pull requests merged in 2023-08, with the labels that each got.

#200 이벤트 등록 기능 구현
  package.json
  public/index.html
  src/assets/artist-default-image.svg
  src/components/AdressInput.tsx
  src/components/AdressInputStyle.ts
  src/components/SelectedElement.tsx
  src/components/modals/AddEventModal.tsx
  src/components/modals/AddEventModalStyle.ts
  src/components/modals/ArtistSelectModal.tsx
  src/components/modals/ArtistSelectModalStyle.tsx
  src/components/modals/CategorySelectModal.tsx
  src/components/modals/CategorySelectModalStyle.tsx
  src/redux/eventApiSlice.ts
  src/redux/setEventElemetsSlice.ts
  src/redux/store.ts
Labels: feature

#202 Fix: 이벤트 등록 완료 시 이벤트 상세 path 수정
  src/components/modals/AddEventModal.tsx
Labels: fix

#194 프로필사진 노출
  src/components/Header.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyPageStyle.tsx
  src/pages/MyPage/components/EditProfile.tsx
Labels: feature

#196 마이페이지 내 이벤트 관련 기능
  src/pages/MyPage/components/Bookmark.tsx
  src/pages/MyPage/components/Event.tsx
  src/redux/bookmarkEventSlice.ts
  src/redux/mypageSlice.ts
Labels: feature

#198 북마크 폴더 공유 기능
  src/assets/icons/logo.svg
  src/assets/icons/memo-back.svg
  src/assets/icons/memo-front.svg
  src/hooks/useRouter.ts
  src/pages/BookmarkShare/BookmarkShare.tsx
  src/pages/BookmarkShare/BookmarkShareStyle.tsx
  src/pages/MyPage/components/Bookmark.tsx
  src/redux/bookmarkFolderSlice.ts
  src/router.tsx
  src/types/bookmarkFolderType.ts
Labels: feature

#203 이벤트 상세 페이지 UI 수정
  src/pages/DetailInfoPage/DetailInfo.tsx
  src/pages/DetailInfoPage/DetailInfoStyle.tsx
  src/pages/DetailInfoPage/ReviewSection.tsx
  src/redux/mypageSlice.ts
Labels: feature, fix

#206 Fix: 아티스트 선택 모달 무한스크롤 버그 해결
  src/components/modals/ArtistSelectModal.tsx
Labels: bug

#208 Fix: 나의 이벤트 UI 깨짐 현상 해결
  src/pages/MyPage/MyPageStyle.tsx
  src/pages/MyPage/components/Event.tsx
  src/pages/MyPage/components/EventStyle.tsx
Labels: bug

#209 이벤트 상세 페이지 기능 구현
  package-lock.json
  package.json
  src/components/KakaoMap.tsx
  src/components/ReviewItem.tsx
  src/pages/DetailInfoPage/DetailInfo.tsx
  src/pages/DetailInfoPage/DetailInfoStyle.tsx
  src/pages/DetailInfoPage/ImageSlider.tsx
  src/pages/DetailInfoPage/InfoSection.tsx
  src/pages/DetailInfoPage/ReviewSection.tsx
  src/pages/DetailInfoPage/TwitterInfoSection.tsx
  src/pages/MyPage/components/EditProfile.tsx
  src/redux/eventApiSlice.ts
  src/redux/eventPlaceSlice.ts
  src/redux/reviewApiSlice.ts
  src/redux/store.ts
  src/types/eventService.ts
Labels: feature, fix

#213 Fix: 변경된 API url 적용
  src/redux/reviewApiSlice.ts
Labels: fix

#219 메인 페이지 기능 구현
  src/assets/marker.svg
  src/components/KakaoMap.tsx
  src/pages/DetailInfoPage/DetailInfo.tsx
  src/pages/DetailInfoPage/ReviewSection.tsx
  src/pages/DetailInfoPage/TwitterInfoSection.tsx
  src/pages/mainPage/Main.tsx
  src/pages/mainPage/ReviewItem.tsx
  src/redux/eventApiSlice.ts
  src/redux/eventPlaceSlice.ts
  src/types/eventService.ts
Labels: feature

#222 리뷰 작성 페이지 UI 수정
  src/assets/icons/ring.svg
  src/assets/icons/tape.svg
  src/assets/icons/thumbtack.svg
  src/components/Rating.tsx
  src/hooks/useInput.ts
  src/pages/editReviewPage/EditReview.tsx
  src/pages/editReviewPage/EditReviewStyle.tsx
  src/redux/reviewApiSlice.ts
  src/router.tsx
Labels: feature, fix

#228 Feat: 리뷰작성 버튼 클릭 시 리뷰작성 페이지로 이동
  src/pages/DetailInfoPage/DetailInfo.tsx
Labels: feature

#232 이벤트 목록 페이지 기능 구현
  src/components/EventListItem.tsx
  src/components/EventListItemStyle.tsx
  src/pages/eventListPage/EventList.tsx
  src/pages/eventListPage/EventListStyle.tsx
  src/redux/eventApiSlice.ts
  src/types/eventService.ts
Labels: feature

#235 전체 리뷰 조회 UI 변경 및 탭 변경시마다 새로운 데이터 불러오도록 수정
  src/components/ReviewRating.tsx
  src/pages/Reviews/ReviewItem.tsx
  src/pages/Reviews/ReviewItemStyle.tsx
  src/pages/Reviews/ReviewStyle.tsx
  src/pages/Reviews/Reviews.tsx
  src/redux/reviewSlice.ts
  src/types/reviewType.ts
Labels: feature

#237 Fix: 나의 리뷰 UI 깨짐현상 해결
  src/pages/MyPage/MyPageStyle.tsx
  src/pages/MyPage/components/Review.tsx
  src/pages/MyPage/components/ReviewStyle.tsx
Labels: fix

#238 Fix: 비밀번호 변경 및 회원정보 수정 UI 변경
  src/pages/MyPage/MyPageStyle.tsx
  src/pages/MyPage/components/ChangePasswordStyle.tsx
  src/pages/MyPage/components/EditProfileStyle.tsx
  src/pages/Reviews/ReviewItem.tsx
  src/pages/Reviews/ReviewItemStyle.tsx
Labels: fix

#239 Feat: 회원정보 수정 요청 후 응답에 따른 alert 처리
  src/pages/MyPage/components/EditProfile.tsx
Labels: bug

#241 react-copy-to-clipboard 적용 및 컴포넌트, 스타일 파일 분리, 폴더 생성시 이름값 유무 확인
  src/components/modals/BookmarkFolderModal.tsx
  src/pages/MyPage/components/Bookmark.tsx
  src/pages/MyPage/components/BookmarkEventItem.tsx
  src/pages/MyPage/components/BookmarkEventItemStyle.tsx
  src/pages/MyPage/components/BookmarkEvents.tsx
  src/pages/MyPage/components/BookmarkEventsStyle.tsx
  src/pages/MyPage/components/BookmarkFolderItem.tsx
  src/pages/MyPage/components/BookmarkFolderItemStyle.tsx
  src/pages/MyPage/components/BookmarkFolders.tsx
  src/pages/MyPage/components/BookmarkFoldersStyle.tsx
  src/pages/MyPage/components/BookmarkStyle.tsx
  src/redux/bookmarkFolderSlice.ts
Labels: enhancement

#244 browser-image-compression 설치 및 이미지 압축 로직 추가
  package-lock.json
  package.json
  src/components/modals/ArtistModal.tsx
  src/components/modals/GroupModal.tsx
  src/pages/MyPage/components/EditProfile.tsx
Labels: enhancement

#246 이벤트 목록 페이지 기능 구현 : 아티스트 모달
  src/assets/color-search-icon.svg
  src/assets/left-arrow.svg
  src/components/ChoiceArtistBar.tsx
  src/components/EventListItem.tsx
  src/components/modals/ArtistListItem.tsx
  src/components/modals/ArtistModal.tsx
  src/components/modals/ArtistSelectModalStyle.tsx
  src/components/modals/CategorySelectModal.tsx
  src/components/modals/EventArtistModal.tsx
  src/components/modals/EventArtistModalStyle.ts
  src/hooks/useScroll.ts
  src/layout/GeneralLayout.tsx
  src/pages/DetailInfoPage/TwitterInfoSection.tsx
  src/pages/ManagePage/ArtistListItem.tsx
  src/pages/SignPage/Signup.tsx
  src/pages/eventListPage/EventList.tsx
  src/redux/artistsSlice.ts
  src/redux/artistsTypeSlice.ts
  src/redux/eventApiSlice.ts
  src/redux/eventPlaceSlice.ts
  src/redux/manageModalSlice.ts
  src/redux/setEventArtistSlice.ts
  src/redux/store.ts
  src/types/artistsType.ts
  src/types/eventService.ts
Labels: feature, fix

#255 리뷰 디테일 페이지 구현
  src/assets/heart-sticker.svg
  src/assets/left-triangle.svg
  src/assets/right-triangle.svg
  src/assets/white-left-arrow.svg
  src/assets/white-right-arrow.svg
  src/components/SketchbookLayout.tsx
  src/pages/DetailInfoPage/ImageSlider.tsx
  src/pages/ReviewDetail/ReviewDetail.tsx
  src/pages/ReviewDetail/ReviewDetailStyle.ts
  src/pages/editReviewPage/EditReview.tsx
  src/pages/editReviewPage/EditReviewStyle.tsx
  src/redux/reviewApiSlice.ts
  src/router.tsx
  src/types/reviewServie.ts
Labels: feature, fix

#252 이미지 압축 로직 변경 및 로딩 UI 추가
  src/assets/icons/timer.svg
  src/components/Loading.tsx
  src/components/modals/ArtistModal.tsx
  src/components/modals/GroupModal.tsx
  src/pages/BookmarkShare/BookmarkShare.tsx
  src/pages/MyPage/components/EditProfile.tsx
  src/pages/MyPage/components/EditProfileStyle.tsx
Labels: enhancement, feature

#269 북마크 기능 추가
  src/components/EventListItem.tsx
  src/components/EventListItemStyle.tsx
  src/components/modals/BookmarkModal.tsx
  src/components/modals/BookmarkModalStyle.tsx
  src/components/modals/CommonModal.tsx
  src/layout/GeneralLayout.tsx
  src/pages/BookmarkShare/BookmarkShare.tsx
  src/pages/BookmarkShare/BookmarkShareStyle.tsx
  src/pages/DetailInfoPage/DetailInfo.tsx
  src/pages/MyPage/components/BookmarkEventItem.tsx
  src/pages/MyPage/components/BookmarkEventItemStyle.tsx
  src/pages/MyPage/components/BookmarkFolderItemStyle.tsx
  src/pages/MyPage/components/Event.tsx
  src/pages/MyPage/components/EventStyle.tsx
  src/pages/MyPage/components/Like.tsx
  src/pages/MyPage/components/LikeStyle.tsx
  src/pages/MyPage/components/ReviewStyle.tsx
  src/redux/addBookmark.ts
  src/redux/bookmarkEventSlice.ts
  src/redux/eventApiSlice.ts
  src/redux/manageModalSlice.ts
  src/redux/store.ts
Labels: feature

#271 이벤트 추가 모달에서 이벤트 페이지로 변경
  src/assets/disabled-map-icon.svg
  src/assets/edit-event-heart.svg
  src/assets/icon-button-plus.svg
  src/components/AdressInput.tsx
  src/components/AdressInputStyle.ts
  src/components/AdressInputStyle.tsx
  src/components/KakaoMap.tsx
  src/components/modals/AddressSearchModal.tsx
  src/components/modals/AddressSearchModalStyle.ts
  src/components/modals/ArtistSelectModal.tsx
  src/components/modals/ArtistSelectModalStyle.tsx
  src/components/modals/CategorySelectModal.tsx
  src/components/modals/EventArtistModal.tsx
  src/layout/GeneralLayout.tsx
  src/pages/EditEvent/EditEvent.tsx
  src/pages/EditEvent/EditEventStyle.ts
  src/pages/eventListPage/EventList.tsx
  src/pages/mainPage/Main.tsx
  src/redux/manageModalSlice.ts
  src/router.tsx
Labels: feature, fix

#273 Feat: 이벤트 추가 페이지 & 리뷰작성 페이지에 이미지 압축 로직 추가
  src/pages/EditEvent/EditEvent.tsx
  src/pages/editReviewPage/EditReview.tsx
Labels: feature

#274 검색 기능 구현
  src/components/AdressInput.tsx
  src/components/modals/ArtistSelectModal.tsx
  src/components/modals/ArtistSelectModalStyle.tsx
  src/components/modals/EventArtistModal.tsx
  src/hooks/useDebounce.ts
  src/hooks/useInput.ts
  src/utils/scrollToTop.ts
Labels: feature

#276 이벤트 수정 구현
  src/pages/EditEvent/EditEvent.tsx
  src/pages/MyPage/components/Event.tsx
  src/redux/apiSlice.ts
  src/redux/eventApiSlice.ts
  src/redux/setEventElemetsSlice.ts
  src/router.tsx
  src/utils/formattingHours.ts
Labels: feature

#280 리뷰 수정/삭제 기능
  src/components/Rating.tsx
  src/pages/MyPage/components/Review.tsx
  src/pages/MyPage/components/ReviewStyle.tsx
  src/pages/editReviewPage/EditReview.tsx
  src/pages/editReviewPage/EditReviewStyle.tsx
  src/redux/reviewApiSlice.ts
  src/router.tsx
Labels: feature

#284 이벤트 디테일 별점 값 추가 및 리뷰 클릭 시 리뷰 상세로 이동
  src/components/ReviewItem.tsx
  src/pages/DetailInfoPage/DetailInfo.tsx
  src/pages/DetailInfoPage/DetailInfoStyle.tsx
Labels: feature

#285 회원가입 기능 redux-toolkit으로 리펙토링
  src/pages/SignPage/Signup.tsx
  src/redux/auth/authApiSlice.ts
Labels: feature, fix

#287 비밀번호 재설정 구현
  src/components/modals/ResetPasswordModal.tsx
  src/pages/ResetPasswordPage/ResetPassword.tsx
  src/pages/SignPage/SignStyle.tsx
  src/pages/SignPage/Signin.tsx
  src/pages/SignPage/Signup.tsx
  src/redux/auth/authApiSlice.ts
Labels: feature, fix

#289 todayHashtags rtk query로 리펙토링
  src/components/Billboard.tsx
  src/redux/eventApiSlice.ts
  src/types/eventService.ts
Labels: fix

#293 헤더 컴포넌트 에러 핸들링
  src/components/Header.tsx
Labels: fix

#294 리뷰페이지 아티스트 선택 및 리뷰 상세페이지로 이동
  src/pages/MyPage/components/Review.tsx
  src/pages/Reviews/ReviewItem.tsx
  src/pages/Reviews/ReviewStyle.tsx
  src/pages/Reviews/Reviews.tsx
Labels: feature

#298 리뷰&이벤트 등록 페이지 취소 버튼 기능 추가
  src/pages/EditEvent/EditEvent.tsx
  src/pages/editReviewPage/EditReview.tsx
Labels: feature

#300 이벤트 북마크 폴더 변경 기능
  src/assets/icons/editpencil.svg
  src/components/modals/BookmarkModal.tsx
  src/layout/GeneralLayout.tsx
  src/pages/MyPage/components/BookmarkEventItem.tsx
  src/pages/MyPage/components/BookmarkEvents.tsx
  src/redux/addBookmark.ts
  src/redux/bookmarkEventSlice.ts
  src/redux/manageModalSlice.ts
Labels: feature

#302 setting 아이콘 깨짐 이슈로 이미지 파일 교체
  src/assets/icons/setting.svg
Labels: fix

#307 인증 필요한 요청 경고창 및 숨기기
  src/components/EventListItem.tsx
  src/pages/DetailInfoPage/DetailInfo.tsx
  src/pages/SignPage/SignStyle.tsx
Labels: fix

#304 회원가입 에러 핸들링
  src/hooks/useForm.ts
  src/pages/SignPage/Signup.tsx
  src/redux/auth/authApiSlice.ts
  src/utils/validates.ts
Labels: fix

#309 Fix: 엔터 눌렀을 때 form 제출 현상 에러 핸들링
  src/components/modals/AddressSearchModal.tsx
  src/components/modals/CommonModal.tsx
Labels: fix

#310 Feat: 공통 배경 스타일링 수정
  src/styles/GlobalStyle.tsx
Labels: feature

#312 헤더, 마이페이지 반응형 작업
  src/components/FixedRating.tsx
  src/components/Header.tsx
  src/pages/MyPage/MyPageStyle.tsx
  src/pages/MyPage/SideBarStyle.tsx
  src/pages/MyPage/components/BookmarkEventItem.tsx
  src/pages/MyPage/components/BookmarkEventItemStyle.tsx
  src/pages/MyPage/components/BookmarkEvents.tsx
  src/pages/MyPage/components/BookmarkEventsStyle.tsx
  src/pages/MyPage/components/BookmarkFolderItem.tsx
  src/pages/MyPage/components/BookmarkFolderItemStyle.tsx
  src/pages/MyPage/components/BookmarkFolders.tsx
  src/pages/MyPage/components/BookmarkFoldersStyle.tsx
  src/pages/MyPage/components/BookmarkStyle.tsx
  src/pages/MyPage/components/ChangePasswordStyle.tsx
  src/pages/MyPage/components/EditProfileStyle.tsx
  src/pages/MyPage/components/Event.tsx
  src/pages/MyPage/components/EventStyle.tsx
  src/pages/MyPage/components/Like.tsx
  src/pages/MyPage/components/LikeStyle.tsx
  src/pages/MyPage/components/Review.tsx
  src/pages/MyPage/components/ReviewStyle.tsx
  src/redux/apiSlice.ts
  src/redux/eventApiSlice.ts
  src/redux/mypageSlice.ts
  src/redux/reviewApiSlice.ts
  src/utils/mediaQuery.ts
Labels: feature

#313 모바일 하단 탭 구현
  src/assets/icons/user.svg
  src/components/MobileTab.tsx
  src/layout/GeneralLayout.tsx
Labels: feature

#318 title 및 favicon 변경
  public/index.html
  public/logo-icon.png
Labels: feature
