Repository duck-map-project/duck-map-fe, pull requests merged in 2023-07, with the labels that each got.

#131 Fix: msw 삭제 및 에러나는 부분 수정
  package-lock.json
  package.json
  src/components/Billboard.tsx
  src/index.tsx
  src/pages/MyPage/MyBookmark.tsx
  src/pages/MyPage/MyEvent.tsx
  src/pages/MyPage/MyInfoEdit.tsx
  src/pages/MyPage/MyLike.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyPageStyle.tsx
  src/pages/MyPage/Myreview.tsx
  src/pages/MyPage/feedData.json
  src/pages/mainPage/Main.tsx
  src/router.tsx
Labels: fix

#132 Feat: icon 이미지 및 font 파일, palette 추가
  src/assets/icons/alarm.svg
  src/assets/icons/comment.svg
  src/assets/icons/delete.svg
  src/assets/icons/edit.svg
  src/assets/icons/event.svg
  src/assets/icons/heart.svg
  src/assets/icons/home.svg
  src/assets/icons/list.svg
  src/assets/icons/login.svg
  src/assets/icons/logout.svg
  src/assets/icons/more.svg
  src/assets/icons/mypage.svg
  src/assets/icons/photo.svg
  src/assets/icons/review.svg
  src/assets/icons/search.svg
  src/assets/icons/setting.svg
  src/assets/icons/star.svg
  src/assets/icons/starIcon.svg
  src/assets/icons/talk.svg
  src/fonts/Roboto-Bold-webfont.woff
  src/fonts/Roboto-Regular-webfont.woff
  src/fonts/SUITE-Bold.woff2
  src/fonts/SUITE-Regular.woff2
  src/fonts/SpoqaHanSansNeo-Bold.woff
  src/fonts/SpoqaHanSansNeo-Light.woff
  src/fonts/SpoqaHanSansNeo-Medium.woff
  src/fonts/SpoqaHanSansNeo-Regular.woff
  src/styles/GlobalStyle.tsx
  src/styles/font.tsx
  src/types/fonts.d.ts
Labels: feature

#133 Feat: 디자인 변경에 따른 UI 변경
  src/assets/close.svg
  src/assets/icon-pencil.svg
  src/assets/icon-pin.svg
  src/assets/kakao-icon.svg
  src/assets/login-icon.svg
  src/assets/logo.svg
  src/assets/naver-icon.svg
  src/assets/review-preview-icon.svg
  src/assets/sort-arrow.svg
  src/assets/sort-book.svg
  src/assets/user-profile.svg
  src/components/AuthInput.tsx
  src/components/Billboard.tsx
  src/components/Dropdown.tsx
  src/components/Header.tsx
  src/components/ResetPasswordModal.tsx
  src/components/SortButton.tsx
  src/components/modals/ModalStyle.tsx
  src/components/modals/ResetPasswordModal.tsx
  src/components/modals/SuccessResetModal.tsx
  src/hooks/useForm.ts
  src/layout/GeneralLayout.tsx
  src/pages/ResetPasswordPage/ResetPassword.tsx
  src/pages/SignPage/SignStyle.tsx
  src/pages/SignPage/Signin.tsx
  src/pages/SignPage/Signup.tsx
  src/pages/mainPage/Main.tsx
  src/pages/mainPage/MainStyle.tsx
  src/pages/mainPage/ReviewItem.tsx
  src/styles/GlobalStyle.tsx
Labels: feature

#135 Feat: 관리자 페이지 UI 구현 및 CRUD 로직 추가
  package.json
  src/assets/icons/delete.svg
  src/assets/icons/edit.svg
  src/assets/icons/manageImage.svg
  src/assets/icons/plus.svg
  src/index.tsx
  src/pages/ManagePage/ArtistListItem.tsx
  src/pages/ManagePage/ArtistListItemStyle.tsx
  src/pages/ManagePage/Manage.tsx
  src/pages/ManagePage/ManageStyle.tsx
  src/redux/apiSlice.ts
  src/redux/artistsSlice.ts
  src/redux/artistsTypeSlice.ts
  src/redux/store.ts
  src/router.tsx
  src/types/artistsType.ts
Labels: feature

#137 Feat: 삭제된 package.json 추가
  package-lock.json
  package.json
Labels: feature

#136 Feat: 아티스트 목록 무한 스크롤 및 header UI, 모달창
  package-lock.json
  package.json
  public/index.html
  src/assets/icons/close.svg
  src/assets/icons/photo.svg
  src/assets/icons/setting.svg
  src/components/Header.tsx
  src/components/modals/AddGroupModal.tsx
  src/components/modals/CommonModal.tsx
  src/layout/GeneralLayout.tsx
  src/pages/ManagePage/ArtistListItem.tsx
  src/pages/ManagePage/Manage.tsx
  src/pages/ManagePage/ManageStyle.tsx
  src/redux/artistsSlice.ts
  src/redux/artistsTypeSlice.ts
  src/redux/manageModalSlice.ts
  src/redux/store.ts
  src/types/artistsType.ts
Labels: bug, feature

#140 Feat: 카카오맵 띄우기
  .eslintrc.json
  package-lock.json
  package.json
  public/index.html
  src/components/KakaoMap.tsx
  src/pages/mainPage/Main.tsx
  tsconfig.json
Labels: feature

#142 이미지 조회/저장 api, 그룹/아티스트 등록 모달 및 기능
  src/components/Dropdown.tsx
  src/components/Header.tsx
  src/components/SortButton.tsx
  src/components/modals/AddArtistModal.tsx
  src/components/modals/AddGroupModal.tsx
  src/components/modals/CommonModal.tsx
  src/layout/GeneralLayout.tsx
  src/pages/ManagePage/ArtistListItem.tsx
  src/pages/ManagePage/ArtistListItemStyle.tsx
  src/pages/ManagePage/Manage.tsx
  src/pages/mainPage/Main.tsx
  src/pages/mainPage/MainStyle.tsx
  src/redux/apiSlice.ts
  src/redux/artistsSlice.ts
  src/redux/artistsTypeSlice.ts
  src/redux/imageSlice.ts
  src/types/artistsType.ts
Labels: feature

#144 Fix: 사용되지 않는 컴포넌트 eslint 에러 및 MapSortDrop 스타일 핸들링
  src/pages/mainPage/Main.tsx
  src/pages/mainPage/MainStyle.tsx
Labels: bug, fix

#146 이벤트카테고리/아티스트 타입 등록 및 아티스트 삭제 기능
  src/components/Header.tsx
  src/components/modals/AddArtistModal.tsx
  src/components/modals/AddArtistModalStyle.tsx
  src/components/modals/AddArtistTypeModal.tsx
  src/components/modals/AddEventCategoryModal.tsx
  src/components/modals/AddEventCategoryModalStyle.tsx
  src/components/modals/AddGroupModal.tsx
  src/components/modals/AddGroupModalStyle.tsx
  src/components/modals/components/TypeButton.tsx
  src/layout/GeneralLayout.tsx
  src/pages/ManagePage/ArtistListItem.tsx
  src/pages/ManagePage/Manage.tsx
  src/redux/apiSlice.ts
  src/redux/artistsSlice.ts
  src/redux/eventCategoryType.ts
  src/redux/manageModalSlice.ts
Labels: bug, feature

#152 Fix: 이벤트 목록 페이지 UI 수정
  src/assets/artist-arrow.svg
  src/assets/artist-heart.svg
  src/assets/icon-plus.svg
  src/assets/tongs.svg
  src/components/ChoiceArtistBar.tsx
  src/components/ChoiceStarBar.tsx
  src/components/EventListItem.tsx
  src/components/EventListItemDetail.tsx
  src/components/KakaoMap.tsx
  src/components/Tag.tsx
  src/pages/eventListPage/EventList.tsx
  src/pages/eventListPage/EventListStyle.tsx
  src/pages/mainPage/Main.tsx
  src/types/eventService.ts
Labels: fix

#156 Feat: 드롭다운 UI 변경
  src/components/Dropdown.tsx
  src/components/SortButton.tsx
  src/pages/mainPage/Main.tsx
Labels: feature

#157 Fix: 이벤트 상세 페이지 스타일 변경
  src/assets/bookmark-empty.svg
  src/assets/bookmark-filled.svg
  src/assets/empty-heart.svg
  src/assets/filled-heart.svg
  src/assets/map-icon.svg
  src/assets/review-icon.svg
  src/assets/small-heart.svg
  src/assets/star-empty.svg
  src/assets/star-filled.svg
  src/assets/twitter-icon.svg
  src/components/FixedRating.tsx
  src/components/KakaoMap.tsx
  src/components/ReviewItem.tsx
  src/components/TextBoxs.tsx
  src/pages/DetailInfoPage/DetailInfo.tsx
  src/pages/DetailInfoPage/DetailInfoStyle.tsx
  src/pages/DetailInfoPage/InfoSection.tsx
  src/pages/DetailInfoPage/MapSection.tsx
  src/pages/DetailInfoPage/ReviewSection.tsx
Labels: feature, fix

#159 마이페이지 UI 및 중첩라우팅
  src/assets/icons/bookmark.svg
  src/assets/icons/bookmarkFolder.svg
  src/assets/icons/heart-big.svg
  src/assets/icons/heart.svg
  src/assets/icons/location.svg
  src/assets/icons/pencil.svg
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyPageStyle.tsx
  src/pages/MyPage/SideBar.tsx
  src/pages/MyPage/SideBarStyle.tsx
  src/pages/MyPage/components/Bookmark.tsx
  src/pages/MyPage/components/BookmarkStyle.tsx
  src/pages/MyPage/components/Like.tsx
  src/pages/MyPage/components/LikeStyle.tsx
  src/pages/MyPage/components/Review.tsx
  src/pages/MyPage/components/ReviewStyle.tsx
  src/router.tsx
Labels: feature

#163 Fix: onClick 이벤트 MenuButton 으로 이동
  src/components/Header.tsx
Labels: bug, fix

#164 Fix: Signin 컴포넌트에서 useForm 적용 제거
  src/pages/SignPage/Signin.tsx
Labels: fix

#169 사용자 인증 로직 redux toolkit 으로 변경
  package-lock.json
  package.json
  src/components/Header.tsx
  src/index.tsx
  src/pages/SignPage/Signin.tsx
  src/redux/apiSlice.ts
  src/redux/auth/authApiSlice.ts
  src/redux/auth/authSlice.ts
  src/redux/auth/userApiSlice.ts
  src/redux/store.ts
  src/router.tsx
Labels: fix

#177 이벤트 등록 모달 UI
  src/assets/add-image-defalut.svg
  src/assets/magnifier.svg
  src/components/AuthInput.tsx
  src/components/SelectedElement.tsx
  src/components/modals/AddEventModal.tsx
  src/components/modals/ArtistSelectModal.tsx
  src/components/modals/ArtistSelectModalStyle.tsx
  src/components/modals/CategorySelectModal.tsx
  src/components/modals/CategorySelectModalStyle.tsx
  src/components/modals/CommonModal.tsx
  src/layout/GeneralLayout.tsx
  src/pages/eventListPage/EventList.tsx
  src/redux/manageModalSlice.ts
Labels: feature

#180 마이페이지 내 북마크 UI 및 기능 추가
  package-lock.json
  package.json
  src/components/modals/AddBookmarkFolderStyle.tsx
  src/components/modals/BookmarkFolderModal.tsx
  src/layout/GeneralLayout.tsx
  src/pages/MyPage/components/Bookmark.tsx
  src/pages/MyPage/components/BookmarkStyle.tsx
  src/redux/apiSlice.ts
  src/redux/bookmarkEventSlice.ts
  src/redux/bookmarkFolderSlice.ts
  src/redux/editBookmarkFolderSlice.ts
  src/redux/manageModalSlice.ts
  src/redux/store.ts
  src/types/bookmarkEventType.ts
  src/types/bookmarkFolderType.ts
Labels: feature

#188 인증 로직 변경
  src/components/Header.tsx
  src/pages/SignPage/Signin.tsx
  src/redux/apiSlice.ts
  src/redux/auth/authSlice.ts
Labels: feature, fix

#189 마이페이지 기능 추가
  src/pages/MyPage/components/Bookmark.tsx
  src/pages/MyPage/components/ChangePassword.tsx
  src/pages/MyPage/components/EditProfile.tsx
  src/pages/MyPage/components/Event.tsx
  src/pages/MyPage/components/Like.tsx
  src/pages/MyPage/components/Review.tsx
  src/redux/apiSlice.ts
  src/redux/auth/authApiSlice.ts
  src/redux/bookmarkFolderSlice.ts
  src/redux/mypageSlice.ts
  src/types/auth.ts
  src/types/bookmarkFolderType.ts
  src/types/mypageType.ts
Labels: feature

#193 관리자페이지 UI 및 기능 추가
  src/assets/icons/book.svg
  src/components/Dropdown.tsx
  src/components/Header.tsx
  src/components/SortButton.tsx
  src/components/modals/AddArtistModalStyle.tsx
  src/components/modals/ArtistModal.tsx
  src/components/modals/ArtistTypeModal.tsx
  src/components/modals/CategoryModal.tsx
  src/components/modals/GroupModal.tsx
  src/layout/GeneralLayout.tsx
  src/pages/ManagePage/ArtistList.tsx
  src/pages/ManagePage/ArtistListItem.tsx
  src/pages/ManagePage/ArtistTypeList.tsx
  src/pages/ManagePage/ArtistTypeListItem.tsx
  src/pages/ManagePage/ArtistTypeListItemStyle.tsx
  src/pages/ManagePage/ArtistTypeListStyle.tsx
  src/pages/ManagePage/CategoryList.tsx
  src/pages/ManagePage/CategoryListItem.tsx
  src/pages/ManagePage/CategoryListItemStyle.tsx
  src/pages/ManagePage/CategoryListStyle.tsx
  src/pages/ManagePage/Manage.tsx
  src/pages/ManagePage/ManageStyle.tsx
  src/redux/artistsSlice.ts
  src/redux/artistsTypeSlice.ts
  src/redux/auth/authApiSlice.ts
  src/redux/auth/authSlice.ts
  src/redux/editArtistSlice.ts
  src/redux/editArtistTypeSlice.ts
  src/redux/editCategorySlice.ts
  src/redux/eventCategorySlice.ts
  src/redux/manageModalSlice.ts
  src/redux/store.ts
Labels: feature
