Repository duck-map-project/duck-map-fe, pull requests merged in 2023-11, with the labels that each got.

#336 [Refactor] 모달 상태 관리 리팩토링
  src/App.tsx
  src/app/api/store.ts
  src/components/ChoiceArtistBar.tsx
  src/components/EventListItem.tsx
  src/components/Header.tsx
  src/features/artists/modals/ArtistModal.tsx
  src/features/artists/modals/ArtistSelectModal.tsx
  src/features/artists/modals/ArtistTypeModal.tsx
  src/features/artists/modals/EventArtistModal.tsx
  src/features/artists/modals/GroupModal.tsx
  src/features/bookmarks/modals/BookmarkFolderModal.tsx
  src/features/bookmarks/modals/BookmarkModal.tsx
  src/features/categories/modals/CategoryModal.tsx
  src/features/categories/modals/CategorySelectModal.tsx
  src/features/events/modals/AddressSearchModal.tsx
  src/features/modal/ReduxModalRoot.tsx
  src/features/modal/manageModalSlice.ts
  src/features/modal/modalsSlice.ts
  src/hooks/useModal.ts
  src/layout/GeneralLayout.tsx
  src/pages/DetailInfo/DetailInfo.tsx
  src/pages/EditEvent/EditEvent.tsx
  src/pages/ManagePage/Artist/ArtistListItem.tsx
  src/pages/ManagePage/ArtistType/ArtistTypeListItem.tsx
  src/pages/ManagePage/Category/CategoryListItem.tsx
  src/pages/MyPage/Bookmark/BookmarkEventItem.tsx
  src/pages/MyPage/Bookmark/BookmarkFolderItem.tsx
  src/pages/MyPage/Bookmark/BookmarkFolders.tsx
Labels: enhancement

#340 모달 컴포넌트 리팩토링
  src/components/Loading.tsx
  src/components/modal/CommonModal.tsx
  src/components/modal/TypeButton.tsx
  src/features/artists/modals/ArtistModal.tsx
  src/features/artists/modals/ArtistSelectModal.tsx
  src/features/artists/modals/ArtistTypeModal.tsx
  src/features/artists/modals/EventArtistModal.tsx
  src/features/artists/modals/GroupModal.tsx
  src/features/artists/services/artistsApiSlice.ts
  src/features/artists/services/artistsTypeApiSlice.ts
  src/features/bookmarks/modals/BookmarkFolderModal.tsx
  src/features/bookmarks/modals/BookmarkModal.tsx
  src/features/categories/modals/CategoryModal.tsx
  src/features/categories/modals/CategorySelectModal.tsx
  src/features/categories/services/categoryApiSlice.ts
  src/features/events/modals/AddressSearchModal.tsx
  src/hooks/useImageProcessing.ts
  src/pages/ManagePage/Artist/ArtistListItem.tsx
  src/pages/MyPage/EditProfile/EditProfile.tsx
  src/types/artistsType.ts
  src/types/artisttypeType.ts
  src/types/categoryType.ts
  src/utils/apiHelpers.ts
  src/utils/handleErrorResponse.ts
Labels: enhancement, feature

#327 반응형 작업 - (1/2)
  src/assets/shortcuts-arrow.svg
  src/components/AuthInput.tsx
  src/components/ChoiceArtistBar.tsx
  src/components/Dropdown.tsx
  src/components/EventListItem.tsx
  src/components/EventListItemDetail.tsx
  src/components/EventListItemStyle.tsx
  src/components/Header.tsx
  src/components/KakaoMap.tsx
  src/components/SortButton.tsx
  src/components/Tag.tsx
  src/pages/EventList/EventList.tsx
  src/pages/EventList/EventListStyle.tsx
  src/pages/Main/MainStyle.tsx
  src/pages/Main/ReviewItem.tsx
  src/pages/Sign/SignStyle.tsx
  src/pages/Sign/Signin.tsx
  src/pages/Sign/Signup.tsx
  src/utils/mediaQuery.ts
Labels: feature

#346 [refactor] api action error handling
  src/features/auth/services/authApiSlice.ts
  src/features/reviews/services/reviewApiSlice.ts
  src/pages/MyPage/ChangePassword/ChangePassword.tsx
  src/pages/MyPage/EditProfile/EditProfile.tsx
  src/pages/MyPage/Event/Event.tsx
  src/pages/MyPage/Review/Review.tsx
  src/utils/apiHelpers.ts
Labels: enhancement
